<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NuGetAudit>false</NuGetAudit>
    <AssemblyName>UmaVR.Installer</AssemblyName>
    <Version>0.1.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\UmaVR.Management\UmaVR.Management.csproj" />
  </ItemGroup>
</Project>
